import Head from "next/head";

export default function Home() {
  return (
    <div className=" min-h-screen  pt-32">
      <Head>
        <title>Decentralised Exchange</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="font-bold sm:text-6xl text-gray-300 text-4xl leading-none text-center tracking-tight mb-12 ">
        Welcome to&nbsp;
        <span
          className="!bg-clip-text text-transparent"
          style={{
            background:
              "linear-gradient(73.59deg, #C339AC 42.64%, #CD4CB5 54%, #E173C7 77.46%)",
          }}
        >
          thirdweb Swap
        </span>
      </h1>
    </div>
  );
}
